name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build app
        run: |
          npm install
          npm run build

      # - name: Run migrations
      #   run: |
      #     npm run migrate
      #   env:
      #     NODE_ENV: production
      #     DB_HOST: ${{ secrets.DB_HOST }}
      #     DB_USER: ${{ secrets.DB_USER }}
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #     DB_NAME: ${{ secrets.DB_NAME }}

      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage dev
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AUTHORIZATION_ARN: ${{ secrets.AUTHORIZATION_ARN }}